//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrssiNotifier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IrssiNotifier.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string AboutButtonText {
            get {
                return ResourceManager.GetString("AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information can be later seen on settings view.
        /// </summary>
        public static string ApiTokenInfoText {
            get {
                return ResourceManager.GetString("ApiTokenInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Token for Irssi script:.
        /// </summary>
        public static string ApiTokenText {
            get {
                return ResourceManager.GetString("ApiTokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web backend has changed notification settings because of an error. Check the changed settings in settings view..
        /// </summary>
        public static string BackendErrorOccurredText {
            get {
                return ResourceManager.GetString("BackendErrorOccurredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string ConfirmLogoutText {
            get {
                return ResourceManager.GetString("ConfirmLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm logout.
        /// </summary>
        public static string ConfirmLogoutTitle {
            get {
                return ResourceManager.GetString("ConfirmLogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem connecting server. Please check the data connection status of your phone..
        /// </summary>
        public static string ConnectionErrorText {
            get {
                return ResourceManager.GetString("ConnectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try to reconnect by clicking &quot;Retry&quot; below..
        /// </summary>
        public static string ConnectionErrorText2 {
            get {
                return ResourceManager.GetString("ConnectionErrorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection problem.
        /// </summary>
        public static string ConnectionErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButtonText {
            get {
                return ResourceManager.GetString("ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching messages..
        /// </summary>
        public static string ErrorFetchingMessages {
            get {
                return ResourceManager.GetString("ErrorFetchingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching messages: {0}.
        /// </summary>
        public static string ErrorFetchingMessagesEx {
            get {
                return ResourceManager.GetString("ErrorFetchingMessagesEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone is not registered or it&apos;s identification data has been changed. Please re-register..
        /// </summary>
        public static string ErrorGuidNotFound {
            get {
                return ResourceManager.GetString("ErrorGuidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from Google failed. Please check your data connection. Re-registration with another account may not be possible without logging out. Do you want to continue without logging out from Google?.
        /// </summary>
        public static string ErrorLogoutFailed {
            get {
                return ResourceManager.GetString("ErrorLogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using an old version of application. Upgrade app to continue..
        /// </summary>
        public static string ErrorOldVersionDialogText {
            get {
                return ResourceManager.GetString("ErrorOldVersionDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using an old version of application. To continue you must upgrade the application to the latest version..
        /// </summary>
        public static string ErrorOldVersionText {
            get {
                return ResourceManager.GetString("ErrorOldVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old version.
        /// </summary>
        public static string ErrorOldVersionTitle {
            get {
                return ResourceManager.GetString("ErrorOldVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on registration: {0}.
        /// </summary>
        public static string ErrorRegistration {
            get {
                return ResourceManager.GetString("ErrorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the data connection of your phone and try registration again later..
        /// </summary>
        public static string ErrorRegistrationTryAgain {
            get {
                return ResourceManager.GetString("ErrorRegistrationTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account not found. Please re-register..
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front page.
        /// </summary>
        public static string FrontPageTitle {
            get {
                return ResourceManager.GetString("FrontPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string HilitePivotAllTitle {
            get {
                return ResourceManager.GetString("HilitePivotAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string HilitePivotNewTitle {
            get {
                return ResourceManager.GetString("HilitePivotNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRSSI NOTIFIER - hilites &lt;3.
        /// </summary>
        public static string HilitePivotTitle {
            get {
                return ResourceManager.GetString("HilitePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification channel is opened automatically. Other settings can be altered in settings view..
        /// </summary>
        public static string InfoNotificationChannelAutoOpened {
            get {
                return ResourceManager.GetString("InfoNotificationChannelAutoOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile has been deleted. Live tile notifications are disabled..
        /// </summary>
        public static string LiveTileRemovedText {
            get {
                return ResourceManager.GetString("LiveTileRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Notification Channel....
        /// </summary>
        public static string LoadingChannelText {
            get {
                return ResourceManager.GetString("LoadingChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting server....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutButtonText {
            get {
                return ResourceManager.GetString("LogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string MoreButtonText {
            get {
                return ResourceManager.GetString("MoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use Live tile notifications you must pin Live tile into main screen. By selecting Ok live tile is created automatically..
        /// </summary>
        public static string PinLiveTileText {
            get {
                return ResourceManager.GetString("PinLiveTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm pin of live tile.
        /// </summary>
        public static string PinLiveTileTitle {
            get {
                return ResourceManager.GetString("PinLiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are forwarded to Google login page. Google doesn&apos;t reveal your password or any other private information for this application. Login is only used for identifying users. Google provides only anonyme identification information for this application..
        /// </summary>
        public static string PrivacyStatementText {
            get {
                return ResourceManager.GetString("PrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy statement..
        /// </summary>
        public static string PrivacyStatementTitle {
            get {
                return ResourceManager.GetString("PrivacyStatementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryButtonText {
            get {
                return ResourceManager.GetString("RetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum time between toast notifications.
        /// </summary>
        public static string SettingsMinimumToastIntervalHeader {
            get {
                return ResourceManager.GetString("SettingsMinimumToastIntervalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines minimum time how often toast notifications are displayed..
        /// </summary>
        public static string SettingsMinimumToastIntervalText {
            get {
                return ResourceManager.GetString("SettingsMinimumToastIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications.
        /// </summary>
        public static string SettingsPushNotificationHeader {
            get {
                return ResourceManager.GetString("SettingsPushNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on/off push notifications..
        /// </summary>
        public static string SettingsPushNotificationText {
            get {
                return ResourceManager.GetString("SettingsPushNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile notifications.
        /// </summary>
        public static string SettingsTileNotificationHeader {
            get {
                return ResourceManager.GetString("SettingsTileNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile push notifications update the application&apos;s tile displayed in the Start Screen by telling count of unread messages. The tile must be pinned to start screen..
        /// </summary>
        public static string SettingsTileNotificationText {
            get {
                return ResourceManager.GetString("SettingsTileNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast notifications.
        /// </summary>
        public static string SettingsToastNotificationHeader {
            get {
                return ResourceManager.GetString("SettingsToastNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast push notifications show notification message in the top of the screen for ten seconds..
        /// </summary>
        public static string SettingsToastNotificationText {
            get {
                return ResourceManager.GetString("SettingsToastNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to allow app to use toast notifications?.
        /// </summary>
        public static string ToastNotificationPermissionText {
            get {
                return ResourceManager.GetString("ToastNotificationPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow toast notifications.
        /// </summary>
        public static string ToastNotificationPermissionTitle {
            get {
                return ResourceManager.GetString("ToastNotificationPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for configuring Irssi and installing Irssi script can be found from website:.
        /// </summary>
        public static string WebsiteHelpInfoText {
            get {
                return ResourceManager.GetString("WebsiteHelpInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the app you must register your phone for web backend..
        /// </summary>
        public static string WelcomeText1 {
            get {
                return ResourceManager.GetString("WelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google account is needed for registration and using of this app..
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Register&quot; to continue..
        /// </summary>
        public static string WelcomeText3 {
            get {
                return ResourceManager.GetString("WelcomeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeTextTitle {
            get {
                return ResourceManager.GetString("WelcomeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which tile template you wish to use.
        /// </summary>
        public static string Wp8TileSelectionText {
            get {
                return ResourceManager.GetString("Wp8TileSelectionText", resourceCulture);
            }
        }
    }
}
