//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrssiNotifier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IrssiNotifier.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoja....
        /// </summary>
        public static string AboutButtonText {
            get {
                return ResourceManager.GetString("AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tämä tieto on myöhemmin nähtävillä asetusnäkymässä..
        /// </summary>
        public static string ApiTokenInfoText {
            get {
                return ResourceManager.GetString("ApiTokenInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Token irssi-skriptiä varten:.
        /// </summary>
        public static string ApiTokenText {
            get {
                return ResourceManager.GetString("ApiTokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-sovellus on muuttanut notifikaatioasetuksia aiemmin sattuneen virheen vuoksi. Tarkista asetukset asetusnäkymässä..
        /// </summary>
        public static string BackendErrorOccurredText {
            get {
                return ResourceManager.GetString("BackendErrorOccurredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruuta.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oletko varma että haluat kirjautua ulos?.
        /// </summary>
        public static string ConfirmLogoutText {
            get {
                return ResourceManager.GetString("ConfirmLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahvista uloskirjautuminen.
        /// </summary>
        public static string ConfirmLogoutTitle {
            get {
                return ResourceManager.GetString("ConfirmLogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jatka.
        /// </summary>
        public static string ContinueButtonText {
            get {
                return ResourceManager.GetString("ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe viestien noutamisessa.
        /// </summary>
        public static string ErrorFetchingMessages {
            get {
                return ResourceManager.GetString("ErrorFetchingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe viestien noutamisessa: {0}.
        /// </summary>
        public static string ErrorFetchingMessagesEx {
            get {
                return ResourceManager.GetString("ErrorFetchingMessagesEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puhelintasi ei ole rekisteröity palveluun tai sen tunniste on muuttunut. Ole hyvä ja kirjaudu uudelleen..
        /// </summary>
        public static string ErrorGuidNotFound {
            get {
                return ResourceManager.GetString("ErrorGuidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe rekisteröinnissä: {0}.
        /// </summary>
        public static string ErrorRegistration {
            get {
                return ResourceManager.GetString("ErrorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjätietojasi ei löytynyt palvelusta. Ole hyvä ja kirjaudu uudelleen..
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etusivu.
        /// </summary>
        public static string FrontPageTitle {
            get {
                return ResourceManager.GetString("FrontPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaikki.
        /// </summary>
        public static string HilitePivotAllTitle {
            get {
                return ResourceManager.GetString("HilitePivotAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uudet.
        /// </summary>
        public static string HilitePivotNewTitle {
            get {
                return ResourceManager.GetString("HilitePivotNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRSSI NOTIFIER - hailaitteja &lt;3.
        /// </summary>
        public static string HilitePivotTitle {
            get {
                return ResourceManager.GetString("HilitePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifikaatiokanava avataan automaattisesti. Tarkista asetusnäkymästä muut asetukset..
        /// </summary>
        public static string InfoNotificationChannelAutoOpened {
            get {
                return ResourceManager.GetString("InfoNotificationChannelAutoOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livetiili poistettu. Poistetaan livetiili-päivitykset käytöstä..
        /// </summary>
        public static string LiveTileRemovedText {
            get {
                return ResourceManager.GetString("LiveTileRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjautuminen.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjaudu ulos.
        /// </summary>
        public static string LogoutButtonText {
            get {
                return ResourceManager.GetString("LogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisää....
        /// </summary>
        public static string MoreButtonText {
            get {
                return ResourceManager.GetString("MoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttääksesi livetiilitoimintoa sinun on kiinnitettävä tiili aloitusnäyttöön. Valitsemalla OK sovellus luo livetiilen automaattisesti..
        /// </summary>
        public static string PinLiveTileText {
            get {
                return ResourceManager.GetString("PinLiveTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahvista tiilen lisäys.
        /// </summary>
        public static string PinLiveTileTitle {
            get {
                return ResourceManager.GetString("PinLiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinut ohjataan Googlen kirjautumissivulle. Google ei välitä tälle sovellukselle salasanaasi eikä muitakaan tilitietojasi. Kirjautumista käytetään ainoastaan käyttäjien yksilöintiin. Google välittää tälle sovellukselle ainoastaan anonyymejä yksilöintitietoja..
        /// </summary>
        public static string PrivacyStatementText {
            get {
                return ResourceManager.GetString("PrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietosuoja.
        /// </summary>
        public static string PrivacyStatementTitle {
            get {
                return ResourceManager.GetString("PrivacyStatementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päivitä.
        /// </summary>
        public static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekisteröidy.
        /// </summary>
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asetukset.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponnahdusviestien vähimmäisväli.
        /// </summary>
        public static string SettingsMinimumToastIntervalHeader {
            get {
                return ResourceManager.GetString("SettingsMinimumToastIntervalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Määrittelee miten pitkä aika kahden ponnahdusviestin välillä tulee vähintään olla..
        /// </summary>
        public static string SettingsMinimumToastIntervalText {
            get {
                return ResourceManager.GetString("SettingsMinimumToastIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifikaatiopalvelu.
        /// </summary>
        public static string SettingsPushNotificationHeader {
            get {
                return ResourceManager.GetString("SettingsPushNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaa/Sulje notifikaatiokanava kokonaan.
        /// </summary>
        public static string SettingsPushNotificationText {
            get {
                return ResourceManager.GetString("SettingsPushNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livetiili.
        /// </summary>
        public static string SettingsTileNotificationHeader {
            get {
                return ResourceManager.GetString("SettingsTileNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päivittää aloitusvalikkoon kiinnitettyä livetiiltä kertoen lukemattomien viestien lukumäärän. Päälle kytkeminen vaatii livetiilen kiinnittämistä päävalikkoon..
        /// </summary>
        public static string SettingsTileNotificationText {
            get {
                return ResourceManager.GetString("SettingsTileNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asetukset.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponnahdusviestit.
        /// </summary>
        public static string SettingsToastNotificationHeader {
            get {
                return ResourceManager.GetString("SettingsToastNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näyttää ponnahdusviestin näytön yläreunassa 10 sekunnin ajan..
        /// </summary>
        public static string SettingsToastNotificationText {
            get {
                return ResourceManager.GetString("SettingsToastNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko antaa sovelluksen käyttää ponnahdusviestipalvelua?.
        /// </summary>
        public static string ToastNotificationPermissionText {
            get {
                return ResourceManager.GetString("ToastNotificationPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salli ponnahdusviestit.
        /// </summary>
        public static string ToastNotificationPermissionTitle {
            get {
                return ResourceManager.GetString("ToastNotificationPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohjeet irssin konfiguroinnista ja skriptin asentamisesta löytyvät sovelluksen verkkosivuilta:.
        /// </summary>
        public static string WebsiteHelpInfoText {
            get {
                return ResourceManager.GetString("WebsiteHelpInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttääksesi sovellusta tulee sinun rekisteröidä puhelimesi palvelun käyttäjäksi..
        /// </summary>
        public static string WelcomeText1 {
            get {
                return ResourceManager.GetString("WelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekisteröimiseen ja sovelluksen käyttämiseen tarvitset Google-tunnukset..
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikkaa &quot;Rekisteröidy&quot; jatkaaksesi..
        /// </summary>
        public static string WelcomeText3 {
            get {
                return ResourceManager.GetString("WelcomeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tervetuloa.
        /// </summary>
        public static string WelcomeTextTitle {
            get {
                return ResourceManager.GetString("WelcomeTextTitle", resourceCulture);
            }
        }
    }
}
